"""empty message

Revision ID: 1a46745e9376
Revises: d4b8d6c19646
Create Date: 2026-05-06 13:19:38.390724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a46745e9376'
down_revision = 'd4b8d6c19646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
        batch_op.alter_column('total',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
        batch_op.alter_column('grand_total',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', mysql.FLOAT(), nullable=False))

    with op.batch_alter_table('voucher_items', schema=None) as batch_op:
        batch_op.alter_column('grand_total',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
