"""empty message

Revision ID: c8d3a09b42d3
Revises: 1a46745e9376
Create Date: 2026-05-06 15:41:31.346608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d3a09b42d3'
down_revision = '1a46745e9376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Numeric(precision=10, scale=4), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###
